name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set environment variables
        run: |
          echo "PERPLEXITY_API_KEY=${{ secrets.PERPLEXITY_API_KEY }}" >> $GITHUB_ENV
          echo "ELEVENLABS_API_KEY=${{ secrets.ELEVENLABS_API_KEY }}" >> $GITHUB_ENV
          echo "PODBEAN_CLIENT_ID=${{ secrets.PODBEAN_CLIENT_ID }}" >> $GITHUB_ENV
          echo "PODBEAN_CLIENT_SECRET=${{ secrets.PODBEAN_CLIENT_SECRET }}" >> $GITHUB_ENV

      - name: Make deploy script executable
        run: chmod +x deployment/deploy.sh

      - name: Deploy to AWS
        run: ./deployment/deploy.sh